# Generated by Django 2.2 on 2020-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('M', 'Multiple Choice'), ('TF', 'True/False'), ('S', 'Subjective')], default='M', max_length=2),
        ),
    ]
